M48
; DRILL file {KiCad (6.0.7-1)-1} date Friday, November 04, 2022 at 01:47:10 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-04T13:47:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.700
%
G90
G05
T1
X6.5Y-44.025
X6.5Y-96.025
X81.5Y-44.025
X81.5Y-96.025
T0
M30
